### ISSUE TITLE
Wrong xFormers version

### ISSUE THREAD

**Issue by freezurbern** [grokuku/stable-diffusion#34]
Using web UI 2 (automatic1111) gives an error message about the wrong xFormers version. How should I fix this, other than disabling xformers in the launch parameters? Thanks!

**Error message in the web UI:**
![image](https://github.com/grokuku/stable-diffusion/assets/6363417/a0618f23-1835-4071-8eb1-e0f1b0928c6c)

**Error message during first container run:**
```
sd-webui-1  | Launching Web UI with arguments: --listen --port 9000 --enable-insecure-extension-access --medvram --xformers --api
sd-webui-1  | WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
sd-webui-1  |     PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.2.1+cu121)
sd-webui-1  |     Python  3.11.7 (you have 3.11.8)
sd-webui-1  |   Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
sd-webui-1  |   Memory-efficient attention, SwiGLU, sparse and more won't be available.
sd-webui-1  |   Set XFORMERS_MORE_DETAILS=1 for more details
```

**Below is my docker-compose.yml:**
```
  sd-webui:
    image: holaflenain/stable-diffusion:latest
    restart: unless-stopped
    environment:
      - WEBUI_VERSION=02
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - ./appdata/sd-webui:/config
    ports:
      - 9000:9000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
